import type { ReactNode } from 'react'
import type { VrpcError } from './errors'

// --------------------------------------------------------
// Underlying client (vrpc ships no types; this is the
// surface vrpc-react relies on, verified against vrpc 3.7.0)
// --------------------------------------------------------

export interface VrpcLogger {
  debug: (...args: unknown[]) => void
  info: (...args: unknown[]) => void
  warn: (...args: unknown[]) => void
  error: (...args: unknown[]) => void
}

export interface VrpcCallOptions {
  functionName: string
  args?: unknown[]
  className?: string
  agent?: string
}

export interface VrpcClient {
  connect: () => Promise<void>
  end: () => Promise<void>
  create: (options: {
    className: string
    instance?: string
    args?: readonly unknown[]
    agent?: string
    cacheProxy?: boolean
    isIsolated?: boolean
  }) => Promise<any>
  getInstance: (
    instance: string,
    options?: { className?: string, agent?: string, noWait?: boolean }
  ) => Promise<any>
  delete: (
    instance: string,
    options?: { className?: string, agent?: string }
  ) => Promise<boolean>
  callStatic: (options: VrpcCallOptions) => Promise<any>
  callAll: (
    options: VrpcCallOptions
  ) => Promise<Array<{ id: string, val: any, err: string | null }>>
  getAvailableAgents: (options?: { mustBeOnline?: boolean }) => string[]
  getAvailableClasses: (options?: {
    agent?: string
    mustBeOnline?: boolean
  }) => string[]
  getAvailableInstances: (options?: {
    className?: string
    agent?: string
    mustBeOnline?: boolean
  }) => string[]
  getClientId: () => string
  on: (event: string, listener: (...args: any[]) => void) => this
  once: (event: string, listener: (...args: any[]) => void) => this
  off: (event: string, listener: (...args: any[]) => void) => this
  removeListener: (event: string, listener: (...args: any[]) => void) => this
}

// --------------------------------------------------------
// Configuration
// --------------------------------------------------------

export interface VrpcBackendConfig {
  /** Name of the agent that serves the class */
  agent: string
  /** Name of the remotely registered class */
  className: string
  /** Named instance to use (see the 4 backend architectures) */
  instance?: string
  /** Constructor arguments; providing this makes the backend active (it creates the instance) */
  args?: readonly unknown[]
}

export interface VrpcConfig<
  B extends Record<string, VrpcBackendConfig> = Record<
    string,
    VrpcBackendConfig
  >
> {
  /** VRPC domain, default 'vrpc' */
  domain?: string
  /** MQTT broker WebSocket URL, default 'wss://broker.hivemq.com:8884/mqtt' */
  broker?: string
  /** Declarative backend mapping, default {} */
  backends?: B
  /** Custom identity announced to the VRPC system */
  identity?: string
  /** Explicit MQTT client id (auto-generated by default) */
  mqttClientId?: string
  /** Use MQTT QoS 0 (fire-and-forget), default true */
  bestEffort?: boolean
  /** Only accept backend instances that publish a schema, default false */
  requiresSchema?: boolean
  /** RPC / connect timeout in ms (vrpc default: 12000) */
  timeout?: number
  /** MQTT keepalive in seconds (vrpc default: 30) */
  keepalive?: number
  /** Logger passthrough to the vrpc client */
  log?: 'console' | VrpcLogger
  /** Verbose logging of lifecycle events, default false */
  debug?: boolean
}

export interface VrpcProviderProps {
  children: ReactNode
  username?: string
  password?: string
  /**
   * Called for connection problems and backend lifecycle errors.
   * Identity changes never affect the connection (consumed via ref).
   */
  onError?: (error: VrpcError) => void
}

// --------------------------------------------------------
// Statuses & results
// --------------------------------------------------------

export type BackendStatus = 'connecting' | 'ready' | 'offline' | 'error'
export type ClientStatus = 'connecting' | 'connected' | 'offline' | 'error'

/** Maps a class's methods to their remote, Promise-returning counterparts */
export type Proxied<T> = {
  [K in keyof T as T[K] extends (...args: any[]) => any ? K : never]: T[K] extends (
    ...args: infer A
  ) => infer R
    ? (...args: A) => Promise<Awaited<R>>
    : never
}

/** Untyped fallback proxy */
export type VrpcProxy = Record<string, (...args: any[]) => Promise<any>>

export interface UseBackendResult<P> {
  /** Proxy of the remote instance; null while connecting or unavailable */
  backend: P | null
  /** Non-null while status is 'offline' or 'error' */
  error: VrpcError | null
  status: BackendStatus
}

export interface VrpcManager<T = VrpcProxy> {
  create: (
    id: string,
    options?: {
      args?: readonly unknown[]
      className?: string
      agent?: string
    }
  ) => Promise<Proxied<T>>
  get: (id: string) => Promise<Proxied<T>>
  delete: (id: string) => Promise<boolean>
  callStatic: (<R = unknown>(
    functionName: string,
    ...args: unknown[]
  ) => Promise<R>) &
  (<R = unknown>(options: VrpcCallOptions) => Promise<R>)
  callAll: (<R = unknown>(
    functionName: string,
    ...args: unknown[]
  ) => Promise<Array<{ id: string, val: R, err: string | null }>>) &
  (<R = unknown>(
    options: VrpcCallOptions
  ) => Promise<Array<{ id: string, val: R, err: string | null }>>)
  /** Immutable snapshot of the currently existing instance ids */
  readonly ids: readonly string[]
}

export interface UseManagerResult<T = VrpcProxy> {
  /** The manager object; always non-null and referentially stable */
  backend: VrpcManager<T>
  /** Reactive immutable snapshot of instance ids */
  ids: readonly string[]
  error: VrpcError | null
  status: BackendStatus
}

export interface UseClientResult {
  /** The underlying VrpcClient; null only before the connection effect ran */
  client: VrpcClient | null
  status: ClientStatus
  /** Last connection-level error (e.g. NETWORK_ERROR), null when healthy */
  error: VrpcError | null
}

// --------------------------------------------------------
// Type-level routing of backend keys
// --------------------------------------------------------

/** Keys configured as multi-instance managers (neither `instance` nor `args`) */
export type ManagerKeys<B> = {
  [K in keyof B]: B[K] extends { instance: string }
    ? never
    : B[K] extends { args: readonly unknown[] }
      ? never
      : K
}[keyof B]

/** Keys configured as instance backends (architectures 1 - 3) */
export type InstanceKeys<B> = Exclude<keyof B, ManagerKeys<B>>

export interface UseBackendHook<B extends Record<string, VrpcBackendConfig>> {
  /**
   * Proxy of one managed instance of a multi-instance backend.
   * Passing `undefined` (no instance selected yet) is allowed and
   * yields a `connecting` result - hooks cannot be called conditionally.
   */
  <T = VrpcProxy>(
    name: ManagerKeys<B> & string,
    id: string | undefined
  ): UseBackendResult<Proxied<T>>
  /** Manager object of a multi-instance backend */
  <T = VrpcProxy>(name: ManagerKeys<B> & string): UseManagerResult<T>
  /** Proxy of an instance backend (anonymous, active or passive) */
  <T = VrpcProxy>(name: InstanceKeys<B> & string): UseBackendResult<Proxied<T>>
}
